# Set value of N to 50
N = 50

# Create a range  from 1 to N with a step of 0.1
S = range(1.0, N, step=0.1)

# Create a range of  from 0.1 to 0.9  with 100 points in total
o = range(0.1, 0.9, length=100)

# Define a function L(S, o) that calculates the log-likelihood based on the given formula
L(S, o) = S * log(o) + (N - S) * log(1.0 - o)

# Load the Plots package and set the backend to use GR for plotting
using Plots
gr()

# Create a heatmap plot 
# The heatmap is generated by evaluating the L(S, o) function for all combinations of S and o
# The color palette used is "jet"
p2 = Plots.heatmap(S, o, (S, o) -> L(S, o), color=:jet, xlabel="S", ylabel="θ", title="Bird's Eye view")

# Set SS to 25 (value of S for the vertical line)
SS = 25

# Add a vertical line to the heatmap at S = 25
vline!([SS], label=false, color=:black)

# Create a plot of L(o|S=25)
P3 = Plots.plot(o, o->L(SS, o), label=false, xlabel='o', title="L(o|S=$SS)")

# Combine the heatmap plot and the L(o|S=25)
Plots.plot(p2, P3)

# Save the combined plot as a PNG image
savefig("./pictures/mle-juliaa.png")
